### ISSUE TITLE
[Hotfix] 회원가입 시 생성되는 이미지 경로 수정

### ISSUE THREAD

**Issue by EomYoosang** [BaedalMate/BeadalMate_Server#213]
## Describe the bug
이미지가 db에 저장될 때 /images가 prefix로 붙어서 적용됨
저장 시 /images prefix 제거 및 애플 로그인에 사용되는 default 이미지 추가 필요

## Todo
- [x] 회원가입시 db 저장 이미지 이름 prefix 제거
- [ ] 애플 회원가입 시 default 이미지 등록
- [ ] dev 서버에 default이미지 업로드

**Comment by EomYoosang** [comment]
애플 로그인 완료 후 2, 3 기능 구현
