### ISSUE TITLE
[Hotfix] 마감된 모집글 우선순위 낮추기

### ISSUE THREAD

**Issue by EomYoosang** [BaedalMate/BeadalMate_Server#314]
## Describe the bug
마감된 모집글은 우선순위 낮추기

## Todo
- [x] 메인페이지 모집글 리스트 수정
- [x] 태그 포함된 메인페이지 모집글 리스트 수정
- [x] 카테고리 별 모집글 리스트 수정
