### ISSUE TITLE
[Hotfix] 마감 시간 기준

### ISSUE THREAD

**Issue by EomYoosang** [BaedalMate/BeadalMate_Server#339]
## Describe the bug
마감 기준이 시간이고 참여자가 없을 경우 실패처리

## Todo
- [x] closeBySchedule 수정
- [x] 태그 한 개 이상 필수로 변경
- [x] 모집글 수정 시 이미지도 변경
- [x] 모집글 상세 정보에 채팅방 id 추가
- [x] 모집글 취소, 참여 취소 시 채팅방 삭제
- [x] 알림 텍스트 변경
