### ISSUE TITLE
[Hotfix] 메세지 타입 필터

### ISSUE THREAD

**Issue by EomYoosang** [BaedalMate/BeadalMate_Server#349]
## Describe the bug
메세지 TALK타입만 조회 하도록 변경,
deactivate date 체킹 안되는 오류,
스웨거 nullable 표시

## Todo
- [x] 메세지 TALK타입만 조회 하도록 변경
- [x] deactivate date 체킹 안되는 오류
- [x] 스웨거 nullable 표시
