### ISSUE TITLE
[Feature] 모집글 상세 조회 기능을 구현한다

### ISSUE THREAD

**Issue by EomYoosang** [BaedalMate/BeadalMate_Server#37]
## Description
모집글 상세 조회 기능을 구현한다

## Todo
- [x] Controller dto 생성
- [x] Controller 메서드 구현
- [x] Swagger 명세 작성
