### ISSUE TITLE
[Feature] 유저 거점 변경 api를 구현한다.

### ISSUE THREAD

**Issue by EomYoosang** [BaedalMate/BeadalMate_Server#71]
## Description
유저 거점 변경 api를 구현한다.
거점 default를 성림학사로 변경한다.
유저 정보 조회 시 score를 추가한다.

## Todo
- [x] User 엔티티에 거점 default 설정
- [x] 유저 거점 변경 api 구현
- [x] 유저 정보 조회 시 response dto 에 유저 평점 추가
