### ISSUE TITLE
[Feature] 모집글 생성 시 이미지 자동 등록을 구현한다.

### ISSUE THREAD

**Issue by EomYoosang** [BaedalMate/BeadalMate_Server#73]
## Description
카테고리 별 이미지 테이블을 생성하고 모집글 생성 시 랜덤 이미지를 매칭한다.

## Todo
- [x] 카테고리별 이미지 테이블 생성
- [x] 카테고리별 이미지 업로드 api 구현
- [x] 이미지 조회 api 구현
- [x] 모집글 생성 시 이미지 랜덤 매칭
- [x] 모집글 조회 시 이미지 추가
